List<Map> checklist = [
  {'question':"Is the rice free of discoloration (brown spots, black specks)?",'checked':false},
  {'question':"Is the rice free of foreign matter (stones, sticks, insects)?",'checked':false},
  {'question':"Is the rice free of broken grains (more than 5%)?",'checked':false},
  {'question':"Is the rice free of visible mold or mildew?",'checked':false},
  {'question':"Is the rice free of excessive moisture (clumping)?",'checked':false},
  {'question':"Is the rice a uniform color (within the expected variety)?",'checked':false},
  {'question':"Is the rice free of off-odors (musty, sour)?",'checked':false},
  {'question':"Is the rice free of discolored grains (yellowish, reddish)?",'checked':false},
  {'question':"Is the rice free of insect fragments?",'checked':false},
  {'question':"Is the rice free of rodent droppings?",'checked':false},
  {'question':"Is the rice free of bird feathers?",'checked':false},
  {'question':"Is the rice free of sand or grit?",'checked':false},
  {'question':"Is the rice free of dust or chaff?",'checked':false},
  {'question':"Is the rice free of any visible signs of damage?",'checked':false},
  {'question':"Is the rice free of any visible signs of moisture damage?",'checked':false},
  {'question':"Is the rice free of any visible signs of insect infestation?",'checked':false},
  {'question':"Is the rice free of any visible signs of rodent infestation?",'checked':false},
  {'question':"Is the rice free of any visible signs of fungal growth?",'checked':false},
  {'question':"Is the rice free of any visible signs of bacterial contamination?",'checked':false},
  {'question':"Is the rice free of any visible signs of chemical contamination?",'checked':false},
  {'question':"Is the rice free of any off-flavors (bitter, sour, rancid)?",'checked':false},
  {'question':"Is the rice free of any metallic or chemical tastes?",'checked':false},
  {'question':"Is the rice free of any fishy or musty odors after cooking?",'checked':false},
  {'question':"Is the rice free of any beany or grassy off-flavors?",'checked':false},
  {'question':"Is the rice free of any unpleasant aftertaste?",'checked':false},
  {'question':"Is the rice free of any gritty texture after cooking?",'checked':false},
  {'question':"Is the rice soft and fluffy after cooking?",'checked':false},
  {'question':"Is the rice free of any hard or undercooked grains?",'checked':false},
  {'question':"Is the rice free of any sticky or gummy grains?",'checked':false},
  {'question':"Is the rice free of any chalky grains (hard, opaque)?",'checked':false},
  {'question':"Is the rice within the acceptable moisture content range for the variety?",'checked':false},
  {'question':"Is the rice within the acceptable broken rice percentage (< 5%)?",'checked':false},
  {'question':"Is the rice within the acceptable head rice percentage (≥ 90%)?",'checked':false},
  {'question':"Is the rice within the acceptable chalkiness percentage (<5%)?",'checked':false},
  {'question':"Is the rice within the expected gelatinization temperature range for the variety?",'checked':false},
  {'question':"Is the rice within the expected amylose content range for the variety?",'checked':false},
  {'question':"Is the rice within the expected volume expansion after cooking?",'checked':false},
  {'question':"Is the rice within the expected cooking time for the variety?",'checked':false},
  {'question':"Is the rice within the expected water absorption rate for the variety?",'checked':false},
  {'question':"Is the rice within the acceptable stickiness index range?",'checked':false},
  {'question':"Is the rice within the acceptable protein content range for the variety?",'checked':false},
  {'question':"Is the rice within the acceptable fat content range for the variety?",'checked':false},
  {'question':"Is the rice within the acceptable ash content range for the variety?",'checked':false},
  {'question':"Is the rice free of aflatoxin levels above regulatory limits?",'checked':false},
  {'question':"Is the rice free of pesticide residue levels above maximum residue limits?",'checked':false},
  {'question':"Is the rice free of heavy metal content (lead, cadmium, etc.) above regulatory limits?",'checked':false},
  {'question':"Is the rice free of arsenic levels above regulatory limits?",'checked':false},
  {'question':"Is the rice free of mycotoxin levels (other than aflatoxin) above safe limits?",'checked':false},
  {'question':"Is the rice free of any detectable levels of genetically modified organisms (GMOs)?",'checked':false},
  {'question':"Is the rice free of any known allergens (e.g., gluten)?",'checked':false},
  {'question':"Is the rice free of E. coli contamination?",'checked':false},
  {'question':"Is the rice free of Salmonella contamination?",'checked':false},
  {'question':"Is the rice free of Staphylococcus aureus contamination?",'checked':false},
  {'question':"Is the rice free of Bacillus cereus contamination?",'checked':false},
  {'question':"Is the rice free of Listeria monocytogenes contamination?",'checked':false},
  {'question':"Is the rice within acceptable limits for total plate count (aerobic bacteria)?",'checked':false},
  {'question':"Is the rice within acceptable limits for mold count?",'checked':false},
  {'question':"Is the rice within acceptable limits for yeast count?",'checked':false},
  {'question':"Is the rice within acceptable limits for Enterobacteriaceae count?",'checked':false},
  {'question':"Is the rice within acceptable limits for Coliform count?",'checked':false},
  {'question':"Is the rice correctly identified as the declared variety (using DNA-based methods)?",'checked':false},
  {'question':"Is the rice free of any off-type grains within the variety?",'checked':false},
  {'question':"Is the rice free of any detectable foodborne pathogens (using DNA methods)?",'checked':false},
  {'question':"Does the rice possess the expected genetic markers related to cooking and eating quality?",'checked':false},
  {'question':"Is the rice free of any undesirable genetic mutations?",'checked':false},
  {'question':"Is the rice within the expected range of genetic diversity for the variety?",'checked':false},
  {'question':"Does the rice match the expected genetic profile for the variety?",'checked':false},
  {'question':"Is the rice free of any evidence of adulteration with other rice varieties?",'checked':false},
  {'question':"Is the rice free of any evidence of genetic engineering not declared on the label?",'checked':false},
  {'question':"Is the rice free of any evidence of irradiation (if not permitted)?",'checked':false},
  {'question':"Is the appearance of cooked rice visually appealing (color, sheen, texture)?",'checked':false},
  {'question':"Is the aroma of cooked rice pleasant and free of off-odors?",'checked':false},
  {'question':"Is the flavor of cooked rice neutral and free of off-flavors?",'checked':false},
  {'question':"Is the texture of cooked rice soft, fluffy, and free of any undesirable qualities?",'checked':false},
  {'question':"Is the chewiness of cooked rice appropriate for the variety?",'checked':false},
  {'question':"Do the grains of cooked rice separate easily?",'checked':false},
  {'question':"Is the overall acceptability of cooked rice high as determined by a trained panel?",'checked':false},
  {'question':"Is the overall acceptability of cooked rice high as determined by consumer surveys?",'checked':false},
  {'question':"Is the rice suitable for the intended cooking methods (e.g., steaming, frying)?",'checked':false},
  {'question':"Is the rice compatible with different dishes?",'checked':false},
  {'question':"Is the rice suitable for making sushi?",'checked':false},
  {'question':"Is the rice suitable for making risotto?",'checked':false},
  {'question':"Is the rice suitable for making rice pudding?",'checked':false},
  {'question':"Is the rice suitable for making fried rice?",'checked':false},
  {'question':"Is the rice suitable for making pilaf?",'checked':false},
  {'question':"Is the rice suitable for making congee?",'checked':false},
  {'question':"Is the rice suitable for making sweet rice dishes?",'checked':false},
  {'question':"Is the rice suitable for making savory rice dishes?",'checked':false},
  {'question':"Is the rice suitable for making ethnic dishes specific to its origin?",'checked':false},
  {'question':"Is the rice suitable for making alcoholic beverages (if applicable)?",'checked':false},
  {'question':"Is the rice free of any detectable levels of radioactive contamination?",'checked':false},
  {'question':"Is the rice free of any detectable levels of microplastics?",'checked':false},
  {'question':"Is the rice free of any detectable levels of nanoplastics?",'checked':false},
  {'question':"Is the rice free of any detectable levels of emerging contaminants?",'checked':false},
  {'question':"Is the rice free of any detectable levels of persistent organic pollutants (POPs)?",'checked':false},
  {'question':"Is the rice free of any detectable levels of endocrine-disrupting chemicals (EDCs)?",'checked':false},
  {'question':"Is the rice free of any detectable levels of pharmaceutical residues?",'checked':false},
  {'question':"Is the rice free of any detectable levels of personal care product residues?",'checked':false},
  {'question':"Is the rice produced and processed in accordance with sustainable agricultural practices?",'checked':false},
  {'question':"Is the rice produced and processed in accordance with ethical and social responsibility standards?",'checked':false},
];